### PR TITLE
FanOfIdol may reincarnate and get rid of Idol

### PR DESCRIPTION
**Pull request by Sunev**
Idol cannot figure out a Fan who died and reincarnated in mode of EndlessYaminabe

### CODE REVIEW

**Comment by uhyo** [comment]
Thank you!
I wonder if we need an implementation of `isCmplType`  for `Player`, which always returns `false`.

**Comment by Sunev** [comment]
Do you mean something like 
```
isCmpType:(type)->
    type == @cmplType?
```

**Comment by uhyo** [comment]
I think calling `pl.isCmplType` will cause an error if `pl` is not a `Complex`.
Just `isCmplType:(type)-> false` would be fine for `Player`?

**Comment by Sunev** [comment]
I don't understand.
What would went wrong with
```
class Player
    isCmplType:(type)->false
```
and
```
class Complex
    isCmplType:(type)->
        type == @cmplType || @main.isCmplType(type) || @sub?.isCmplType(type)
```
, since all other jobs extends from these 2 class.

**Comment by uhyo** [comment]
I'm sorry. I didn't find that `isCmplType` for `Player` was already there.

**Pull request merged**
