### PR TITLE
TypeError: Cannot set property 'from' of null

### PR DESCRIPTION
**Pull request by Sunev**
TypeError: Cannot set property 'from' of null
    at /home/werewolf/jinrou/server/mailer.coffee:51:13

### CODE REVIEW

**Comment by uhyo** [comment]
Thanks, but does [this](https://github.com/uhyo/jinrou/pull/58/commits/f8de86cb9eedc3f83fff981ef2e28ea74488816f#diff-46931ea584e9ab08ce7acdbce014b5e6R128) need to be an error?
It may happen when an user clicked his mail address input but did not make change.
I think in such a case the system should ignore this rather than report an error.

**Comment by Sunev** [comment]
I understand what you mean. I report an error just for convenience.
If we return some ```null``` [here](https://github.com/uhyo/jinrou/pull/58/commits/f8de86cb9eedc3f83fff981ef2e28ea74488816f#diff-46931ea584e9ab08ce7acdbce014b5e6L125), the server would crash because it try to ```set property 'from' of null``` 
You return a ```options: null``` [here](https://github.com/uhyo/jinrou/pull/58/commits/f8de86cb9eedc3f83fff981ef2e28ea74488816f#diff-46931ea584e9ab08ce7acdbce014b5e6L125), this means ```options``` at [Line 51](https://github.com/uhyo/jinrou/pull/58/commits/f8de86cb9eedc3f83fff981ef2e28ea74488816f#diff-46931ea584e9ab08ce7acdbce014b5e6L51) is not an Object

**Comment by Sunev** [comment]
I did not review 054ac7e0f5477156d0ed115d36bae137d5145ef7  very carefully, but it seems this ```makemailobj()``` must return something so

**Comment by uhyo** [comment]
I have understood the error. Some fix is required.
Could you please keep the latter half of [this commit](https://github.com/uhyo/jinrou/pull/58/commits/f8de86cb9eedc3f83fff981ef2e28ea74488816f#diff-46931ea584e9ab08ce7acdbce014b5e6L125) unchanged, so that it returns `{mail: null, options: null}` but the server does not crash thanks to the former half.
I think reporting error is not suitable here, especially in the case where an user click his mail address, made no change on it but changed other part of his profile (e.g. user name). In such a case the user would expect his name to be changed and saved but not to see an error saying his mail address is not changed.

**Comment by Sunev** [comment]
ok, commit came.
I didn't recognize [this](https://github.com/uhyo/jinrou/pull/58/commits/f8de86cb9eedc3f83fff981ef2e28ea74488816f#diff-46931ea584e9ab08ce7acdbce014b5e6L53) before

**Comment by uhyo** [comment]
Thank you!

**Pull request merged**
