### PR TITLE
miko-gone punish

### PR DESCRIPTION
**Pull request by Sunev**
The draw caused by Miko's GONE is pretty annoying.
I guess you have the same idea.

### CODE REVIEW

**Comment by uhyo** [comment]
Does this mean that a Miko who performed miko-gone 3 times is automatically added to norevivers?
I like the idea but I'm not sure how likely it happens.

**Comment by Sunev** [comment]
> Does this mean that a Miko who performed miko-gone 3 times is automatically added to norevivers?

Yes.

Miko who uses his skill at night can resist the sudden death caused by not voting.
I met a guy last night and he left the game after using Miko's skills. After 3 times of voting, the game became a draw. This really angered everyone.

**Comment by Sunev** [comment]
Miko often uses this method to prove his identity, but if this leads to a draw, it will be too much.

**Comment by uhyo** [comment]
Thanks, I understand. I agree with you.

**Pull request merged**
