### PR TITLE
remove zh_cn from language

### PR DESCRIPTION
**Pull request by Sunev**
as it is not up-to-date

### CODE REVIEW

**Comment by uhyo** [comment]
Thank you! Maintaining language data is such a hard work...

**Comment by Sunev** [comment]
Yes, in my fork,I changed ```zh_cn``` into ```ja```. In this way I can track changes more easily.

**Comment by Sunev** [comment]
I'm wondering about that is it necessary to include all i18n in single repository.
Anyway, we don't server all languages at same time.

**Comment by uhyo** [comment]
I think it's not necessary. One can maintain their own language data for their server.
I'm giving language tags to data for less merge conflicts.

**Pull request merged**
